_ALIASES: dict[str, str] = {
    # ESPN → canonical
    "usa": "United States",
    "united states": "United States",
    "south korea": "Korea Republic",
    "korea republic": "Korea Republic",
    "republic of korea": "Korea Republic",
    "iran": "IR Iran",
    "ir iran": "IR Iran",
    "ivory coast": "Côte d'Ivoire",
    "cote d'ivoire": "Côte d'Ivoire",
    "cape verde": "Cabo Verde",
    "democratic republic of congo": "DR Congo",
    "dr congo": "DR Congo",
    "trinidad & tobago": "Trinidad and Tobago",
    "northern ireland": "Northern Ireland",
    "chinese taipei": "Chinese Taipei",
    "new zealand": "New Zealand",
    # eloratings → canonical
    "brazil": "Brazil",
    "france": "France",
    "england": "England",
    "argentina": "Argentina",
    "spain": "Spain",
    "germany": "Germany",
    "portugal": "Portugal",
    "netherlands": "Netherlands",
    "belgium": "Belgium",
    "croatia": "Croatia",
    "morocco": "Morocco",
    "japan": "Japan",
    "mexico": "Mexico",
    "senegal": "Senegal",
    "canada": "Canada",
    "ecuador": "Ecuador",
    "australia": "Australia",
    "poland": "Poland",
    "switzerland": "Switzerland",
    "uruguay": "Uruguay",
    "colombia": "Colombia",
    "venezuela": "Venezuela",
    "chile": "Chile",
    "paraguay": "Paraguay",
    "peru": "Peru",
    "nigeria": "Nigeria",
    "ghana": "Ghana",
    "cameroon": "Cameroon",
    "egypt": "Egypt",
    "algeria": "Algeria",
    "mali": "Mali",
    "tunisia": "Tunisia",
    "saudi arabia": "Saudi Arabia",
    "qatar": "Qatar",
    "indonesia": "Indonesia",
    "turkey": "Turkey",
    "ukraine": "Ukraine",
    "austria": "Austria",
    "denmark": "Denmark",
    "scotland": "Scotland",
    "wales": "Wales",
    "serbia": "Serbia",
    "hungary": "Hungary",
    "czech republic": "Czech Republic",
    "slovakia": "Slovakia",
    "slovenia": "Slovenia",
    "romania": "Romania",
    "greece": "Greece",
    "albania": "Albania",
    "iceland": "Iceland",
    "norway": "Norway",
    "sweden": "Sweden",
    "finland": "Finland",
    "ireland": "Ireland",
    "israel": "Israel",
}


def normalize(name: str) -> str:
    """Return canonical team name, preserving casing of canonical form."""
    key = name.strip().lower()
    return _ALIASES.get(key, name.strip())
